### ISSUE TITLE
[Bug]: longer instructions

### ISSUE THREAD

**Issue by Evan-UHRING** [algosup/2023-2024-project-3-virtual-processor-team-8#15]
### What happened?

If you write the instruction with the complete word (for example, mul will be multiply), it doesn't detect a syntax error and write it as instruction and function name

### Operating System

Windows

### Relevant log output

```shell
==========================================================
Instruction: subtract
Name: act
Parameter 1: rd
Parameter 2: 1
Line: 8
==========================================================
```

### priority

Should be done quickly

**Comment by laurentbouquin** [comment]
Fixed
