### ISSUE TITLE
[Typo]: B part of the Functional Specification

### ISSUE THREAD

**Issue by Evan-UHRING** [algosup/2023-2024-project-3-virtual-processor-team-8#5]
### Which document is concerned?

Functional-Specificaton.md

### What is the typo?

In the B1 part, at the title, it should be "customer's"
In the B1 part, at "the main customer requirement", it should be "the main customer's requirement"
In the B1 part, at "This processor will have be in x86 environment", it should be "This processor will have to be in x86 environment", also it's not a customer's requirement 
In the B2 part, at "customers requirement", it should be "customer's requirement"
In the B2 part, need to replace the '~~'
In the B2 part, at "The main requirements are not up to expectations", "are not up to" should be "not meeting the"
In the B4 part, at the end of the first sentence, "clients device" should be "client's device"
In the B5 part, ".ASM" has to be in lowercase
In the B5 part, at the end of the first sentence, "teams syntax" should be "team's syntax"
In the B5 part, at "to the team projects Github", it should be "to this team's Github repository"
In the B5 part, at the end, change "//LINK" to an actual link
In the B7 part, at the beginning, "virtual" should be "terminal"
In the B7 part, at the end of the sentence, "users device" should be "user's device"
In the B7 part, right next to last issue, "It is" should be "It's" for consistency
In the B7 part, in the last sentence, "As to today" should be "As for today"
In the B8 part, at "keep an virtual", it should be "keep a virtual"
In the B9 part, the word user is inconsistent
In the B9 part, in the box 5.2, "users device" should be "user's device"
In the B9 part, in the box 7.2, change "directory" to "a path"
In the B9 part, in the box 8.2, 8.3 and 3.4, "it's" should be "its"
In the B9 part, "- N.S.T.R" is inconsistent
In the B9 part, in the box 6.4, "an error" should be "any error"
In the B10 part, change "it is" to "it's" for consistency
In the B10 part, at "it's program", it should be "its program"
In the B10 part, at "This functional requirements", "requirements" should not have a 's'
In the B10 part, at "of the users file", it should be "of the user's file"

### priority

Should be done quickly

**Comment by Ianlaur** [comment]
All typo errors have been fixed!
